### ISSUE TITLE
友链和关于页面导航被遮挡

### ISSUE THREAD

**Issue by jiahao-jayden** [volantis-x/hexo-theme-volantis#197] opened 2020-03-23 12:33 UTC
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 
关于和友链页面的导航栏会居中，好像没有看的可以控制导航位置的参数
![image](https://cdn.jsdelivr.net/gh/mrhuanhao/cdn/problem/screenshot2020-03-23_20-29-24.png)

### Node.js and NPM Information

```
npm：6.13.4
node：v12.16.1
```

**Comment by xaoxuu** [comment] 2020-03-23 13:00
Duplicate of #183

**Comment by xaoxuu** [comment] 2020-03-23 13:12
以后会增加参数自己选，现在只能少放一点

**Comment by Charlie-zzy** [comment] 2020-03-24 00:15
@xaoxuu 不如没有侧边栏时仍然让navbar的宽度和有侧边栏时一样？我觉得这样应该可以吧

**Closed as completed** 2020-03-24 04:07 UTC
Labels: duplicate

**Comment by xaoxuu** [comment] 2020-03-24 05:27
刚发布的2.2.1版本中可以选择了。
